import React from 'react'

export const metadata = {
  title: "NumPy Basics - Abhrajit Gupta Blogs",
  description: "Generated by create next app",
};

const numpy = () => {
  return (
    <div className='blogpost container m-auto mt-12 flex flex-col gap-6'>
    <h1 className='text-5xl font-bold text-center'>NumPy Basics</h1>
   <p>In the world of programming, we need to work with arrays majority of the time. NumPy enhances computational efficiency by providing optimized functions and operations for array computing in Python.</p>
  <p>NumPy, short for Numerical Python is a Python library which provides an extensive collection of functions and operations for working with multidimensional arrays and matrices. These arrays are the building blocks for most scientific computing tasks, offering a convenient and efficient way to manipulate large datasets and perform complex mathematical operations.</p>
  <p>Lets delve into NumPy by code part:</p>
  <p>At first, we need Google Colab to run the python codes. Make a new notebook and here you go.</p>
  </div>
  )
}

export default numpy
